### ISSUE TITLE
Silent Arm

### ISSUE THREAD

**Issue by marbaugh** [automaton82/MQTT-concord4#3]
The code that was forked from SmartThings also supported the 'Silent' arm and disarm so the keypad would not beep.  Is that something that can be done here?

**Comment by automaton82** [comment]
Yes it could be added back as an option, but HA doesn't support sending the value. For my alarm system sending ```silent``` doesn't do anything when it changes modes (I never hear beeps), however it does make the alarm itself totally silent when it is tripped.

If you want it silent by default you could fork it and either add the option in, or just change the ```arm_silent = False``` to be ```True``` instead since no value is sent for this option.

**Comment by marbaugh** [comment]
I just found where I can set silent=True.

def ArmDisarm(self, action='stay', arm_silent = True, bypasszone='',partition_num=1):
log.debug("Menu item: Arm/Disarm: %s" % str(action))
